language: php

php:
  - 7.2
  - 5.6

matrix:
  allow_failures:
    - php: 7.2

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" < "7.0" ]]; then pecl install xdebug-2.5.5; fi
  - if [[ "$TRAVIS_PHP_VERSION" = "7.0" ]] || [[ "$TRAVIS_PHP_VERSION" > "7.0" ]]; then pecl install xdebug; fi
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

before_script:
  - composer selfupdate

script:
  - ant composer-init
  - ant build
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml

notifications:
  email: info@appserver.io
  hipchat: 95d47a72c5372d4a0fef20048c3200@Appserver
